spring.application.name=waterMeter-gather
server.port=8090

# application.properties
spring.rabbitmq.host=10.168.56.101
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

water.meterData.key=FwdCumFlow

water.off-line-interval=2880
