spring.application.name=jinanqiao-gather
server.port=8089

# application.properties
spring.rabbitmq.host=10.168.56.101
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

ybtt.token=692cf8618a2a6726cfaef89c
ybtt.private_key=MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANYurgEe3FkShaKTKXrv3DJiD+eQm0Nzk/T38xzB/gcaoSnyxCdo35bYyED4JfCUcQAuEKYkVq2HVXyKQu21wyKcQdC+3hNuyjnmFETH6w+Hm+YIhsJkk/YezZwNUtxw/gfjh2FqzQEdmP2ix82IWhz/9Na094EB2QA+72D2/uFjAgMBAAECgYALpBndAbpkNPeCcJEul17WdjH7Ggb2UY/XHqreA0U1SaM8zm8O3UpZvoqTzWjyfH7vzZEmFo+HevWQgUtF9D0YyPX6cH+EnZTK7KwQXBAh929Ye9pX4LTq5L1c6FOg3Vr8Km8+ZYUc0fhWBztrvu6b1XBhdY117WIZfEjwdzHJ8QJBAPqzoWjVo5XB8T4FZFh/C3J19mWV1eNmNF6Rf94TE7jOt7h3XYxB1BWhRdPlIwP7CDkJvtxg+0dk5wi4WmhUPscCQQDatXgItETvNfTlE4vDeWGwJhXtxRpIM2QzftSf5wLc/jBMvXLszyPl0XvBjqbl8e2IYFHr7TwStSZofkQ2P5yFAkBkMoDzVldwFjhl0l/dosEfeRgGV9FJdmK93Sceyb8bILt65XIlCXZLQs6WtsC86YrKySNYDwa+7QwNhyjTA8CnAkEAsR4ZEWN8GAUoSIPlwe4A8LhHNgFTYXlNAm8KHlzk8rdfwiYCdkjiF3HouT2fZ8TeynzGmzvKVJQjgKgQ8aXeSQJAESI+VlAvqJG/hxIuhm8a0l3XvT7GG9joQOmFA4Imv9LfIWlUKFGCHY2eRnoQHotO8UwxcY6g6+zKf9wGnsJP3Q==
ybtt.public_key=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDWLq4BHtxZEoWikyl679wyYg/nkJtDc5P09/Mcwf4HGqEp8sQnaN+W2MhA+CXwlHEALhCmJFath1V8ikLttcMinEHQvt4Tbso55hREx+sPh5vmCIbCZJP2Hs2cDVLccP4H44dhas0BHZj9osfNiFoc//TWtPeBAdkAPu9g9v7hYwIDAQAB
ybtt.deviceNums=A868892078345932,A868892078329597,A868892078329928,A868892078329761,A868892078329480,A868892078329571,A868892078329019,A868892078345619,A868892078330546,A868892078329126,A868892078329902
ybtt.hostPath=https://link-i.supmea.com/openApi/deviceOpenApi/deviceOpenApi/queryDeviceDetail
