spring.application.name=flow-gather
server.port=8093

# application.properties
spring.rabbitmq.host=10.168.56.101
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

flow.off-line-interval=20
flow.attribute=IF,IHF,FV,MFSV,PCF,NCF,PCH,NCH,NtCF,NtCH,T1/SWT,T2/RWT
