spring.application.name=jinanqiao-gather
server.port=8089

# application.properties
spring.rabbitmq.host=10.168.56.101
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

xxhj.host=http://10.21.1.250
xxhj.username=admin
xxhj.password=admin1234
xxhj.moduleId=c7526e18808ab57b8e5efbbbb5b0a1f2
xxhj.sKey=x759x8923753hjm9
xxhj.ivParameter=x658x6102h874j31
xxhj.deviceTypes=Electricity,Water,Heat
