spring.application.name=jinanqiao-gather
server.port=8092

# application.properties
spring.rabbitmq.host=10.168.56.101
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/

hysw.appId=1998556436199665665
hysw.appSecret=$2a$10$FWsdvIH4PZ0mH2K4o5F3Z.rFerEJJhVf3YuCfITGecs/gTGAQQOty
hysw.host=http://shuibiaocn.com:9999
