server:
  port: 7207
spring:
  application:
    name: sgai-fwbz-dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:fwbz-dev.yaml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        namespace: public
        username:
        password:
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: public
        username:
        password:
        group: DEFAULT_GROUP
mqtt:
  broker: tcp://10.61.13.131:1883
  username: admin
  password: zaq!@wsx
  client-id: sgai-fwbz-mqtt-consumer
  topic: sendData       # ← 订阅主题，默认占位，请改成实际主题
  qos: 1

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: org.jeecg.modules.fwbz.handler